name: Create Alfred Workflow

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Alfred workflow
        id: builder
        uses: mikybars/build-alfred-workflow@v1.1
        with:
          exclude_patterns: "*.pyc *__pycache__/*"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.builder.outputs.workflow_file }}
